media:
  input: public
  output: /

content:
  - name: posts
    label: Blog
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, pubDatetime ]

    fields:
      - name: title
        label: Título
        type: string
        required: true

      - name: slug
        label: URL
        type: string
        required: true

      - name: description
        label: Resumen
        type: string
        required: true
        options:
          maxLength: 180

      - name: image
        label: Imagen principal
        type: image
        required: true

      - name: category
        label: Categoría
        type: select
        options:
          choices:
            - Tecnología
            - Eficiencia
            - Mantenimiento
            - Innovación
            - Casos de Éxito

      - name: pubDatetime
        label: Fecha de publicación
        type: date
        required: true

      - name: draft
        label: Borrador
        type: boolean
        default: true

      - name: tags
        label: Tags
        type: string
        list: true

      - name: body
        label: Contenido
        type: rich-text